print("A 10-digit Python Calculator (Substraction)")
print("• Instructions to use the calculator :-")
print("1. You can substract only 10 digits/numbers in this calculator.")
print("2. Where you do not need to substart numbers, type '0' there.")
print("3. If you need to calculate again, re-start the Terminal.")
print("The Calculator is given in below :-")
num1 = int(input("Give first number : "))
num2 = int(input("Give second number : "))
num3 = int(input("Give third number : "))
num4 = int(input("Give fourth number : "))
num5 = int(input("Give fifth number : "))
num6 = int(input("Give sixth number : "))
num7 = int(input("Give seventh number : "))
num8 = int(input("Give eighth number : "))
num9 = int(input("Give ninth number : "))
num10 = int(input("Give tenth number : "))
result = num1 - num2 - num3 - num4 - num5 - num6 - num7 - num8 - num9 - num10
print(num1,"-",num2,"-",num3,"-",num4,"",num5,"-",num6,"-",num7,"-",num8,"-",num9,"-",num10,"=",result)
print("Re-start Terminal to Calculate again.")